### ISSUE TITLE
VARS_p8 Two correct answers

### ISSUE THREAD

**Issue by King-Inoma** [RunestoneInteractive/thinkcpp#20]
has two correct answers, 1 and 6. It only accepts 6 as the correct answer

**Comment by wrigjl** [comment]
I think the question is right, but it's subtle.

If we pick from:

```
string favClass = "MATH";
string favClass = 'MATH';
```

Only the first one is correct (different in quotes). For the rest:

```
cout << "My favorite class is ";
cout << favClass;
=====
cout << "My favorite class is " << endl;
cout << favClass;
=====
cout << "My favorite class is" << favClass;
```

The first is right, the second is wrong (additional newline), and the third is wrong (needs a space between s and " to be correct).

**Comment by King-Inoma** [comment]
hmm ok that difference was hard to see over discord, I was helping a friend. Ill make sure to check on my to be sure next time.
