### ISSUE TITLE
Do not commit __pycache__ or .pyc files

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/thinkcpp#32]
Committing generated files like this breaks the automated update and build scripts.

**Comment by wrigjl** [comment]
I removed \_\_pycache\_\_ and pyc files from the repo in https://github.com/RunestoneInteractive/thinkcpp/compare/41b29b608888287b022321e33d1d814f8face562...77979e2242cf79221d30ad6d8a620da210f2685a

I also added build and publish to the .gitignore.

I -bet- they are left over on your machine from a previous fetch? They are definitely not present anywhere in the main branch.

**Comment by bnmnetp** [comment]
That could be.  I stashed and pulled so everything ought to be fine now.
