### ISSUE TITLE
time_4 missing closing curly brace

### ISSUE THREAD

**Issue by MikeeyBikeey** [RunestoneInteractive/thinkcpp#37]
https://github.com/RunestoneInteractive/thinkcpp/blob/07dda5e17a100baf2874ed60592ecc0f72d1324c/_sources/Chapter9/time.rst?plain=1#L163C1-L165C12

Line 164 should have a closing curly brace after it to end the function body as part of the correct answer.

![image](https://github.com/RunestoneInteractive/thinkcpp/assets/28787208/22bb2465-93d4-4335-a824-42e1ad55d727)

**Comment by wrigjl** [comment]
fixed slightly differently. I make the } a parsons element in df83f0c
