### ISSUE TITLE
vectors_4 values of vector are default inserted

### ISSUE THREAD

**Issue by MikeeyBikeey** [RunestoneInteractive/thinkcpp#44]
https://github.com/RunestoneInteractive/thinkcpp/blob/796cf1bd941a2b3ef671b27fe16a8e1cc645712e/_sources/Chapter10/vectors.rst?plain=1#L128C1-L144C52

According to cppreference, [constructing a vector](https://en.cppreference.com/w/cpp/container/vector/vector) of a given size will [default insert](https://en.cppreference.com/w/cpp/named_req/DefaultInsertable) its elements. If cppreference is correct, the answer should be '0'.

[Playground](https://cpp.sh/?source=%23include+%3Ciostream%3E%0D%0A%23include+%3Cvector%3E%0D%0Ausing+namespace+std%3B%0D%0A%0D%0Aint+main()+%7B%0D%0A++++vector%3Cint%3E+numbers(6)%3B%0D%0A++++for+(int+n+%3A+numbers)+%7B%0D%0A++++++++cout+%3C%3C+n+%3C%3C+endl%3B%0D%0A++++%7D%0D%0A++++return+0%3B%0D%0A%7D%0D%0A)

**Comment by wrigjl** [comment]
fixed in 8134fbc

It turns out that `vectors_1` was wrong too... strings are also default constructed to be empty.
